### ISSUE TITLE
CSPDarknet53-PANet-SPP

### ISSUE THREAD

**Issue by Seperendity** [SCAU-HuKai/yolov3-spp-annotations#1]
博主请问换了主干和特征融合方法后，相比v3-spp效果如何呢？您有做过结合注意力的改进嘛

**Comment by HuKai97** [comment]
我学的注意力都在这里了，第二节：https://blog.csdn.net/qq_38253797/article/details/119684388
但是效果就不好说了，比较玄学，要一个个试。
